const categories = [
    { name: 'Super', image: 'super' },
    { name: 'Muscle', image: 'muscle' },
    { name: 'Sports', image: 'sports' },
    { name: 'SUV', image: 'suv' },
    { name: 'Sedans', image: 'sedans' },
    { name: 'Compacts', image: 'compacts' },
    { name: 'Off-road', image: 'offroad' },
    { name: 'Motorcycles', image: 'motorcycles' },
];

const cars = [
    { name: 'Adder', model: 'adder', category: 'Super', price: 1000000, image: 'adder' },
    { name: 'Banshee', model: 'banshee', category: 'Sports', price: 150000, image: 'banshee' },
    { name: 'Buffalo', model: 'buffalo', category: 'Muscle', price: 35000, image: 'buffalo' },
    { name: 'Elegy RH8', model: 'elegy2', category: 'Sports', price: 95000, image: 'elegy2' },
    { name: 'Gauntlet', model: 'gauntlet', category: 'Muscle', price: 32000, image: 'gauntlet' },
    { name: 'Futo', model: 'futo', category: 'Sports', price: 9000, image: 'futo' },
    { name: 'Sultan', model: 'sultan', category: 'Sports', price: 12000, image: 'sultan' },
    { name: 'Kuruma', model: 'kuruma', category: 'Sports', price: 95000, image: 'kuruma' },
    { name: 'F620', model: 'f620', category: 'Sports', price: 80000, image: 'f620' },
    { name: 'Schafter V12', model: 'schafter3', category: 'Sedans', price: 65000, image: 'schafter3' },
    { name: 'Zentorno', model: 'zentorno', category: 'Super', price: 725000, image: 'zentorno' },
    { name: 'Infernus', model: 'infernus', category: 'Super', price: 440000, image: 'infernus' },
    { name: 'Massacro', model: 'massacro', category: 'Sports', price: 275000, image: 'massacro' },
    { name: 'Jester', model: 'jester', category: 'Sports', price: 240000, image: 'jester' },
    { name: 'Penumbra', model: 'penumbra', category: 'Sports', price: 24000, image: 'penumbra' },
    { name: 'Dominator', model: 'dominator', category: 'Muscle', price: 35000, image: 'dominator' },
    { name: 'Fugitive', model: 'fugitive', category: 'Sedans', price: 24000, image: 'fugitive' },
    { name: 'Baller', model: 'baller', category: 'SUV', price: 90000, image: 'baller' },
    { name: 'Cavalcade', model: 'cavalcade', category: 'SUV', price: 60000, image: 'cavalcade' },
    { name: 'Alpha', model: 'alpha', category: 'Sports', price: 150000, image: 'alpha' },
    { name: 'Blista', model: 'blista', category: 'Compacts', price: 16000, image: 'blista' },
    { name: 'Carbonizzare', model: 'carbonizzare', category: 'Sports', price: 195000, image: 'carbonizzare' },
    { name: 'Comet', model: 'comet2', category: 'Sports', price: 100000, image: 'comet2' },
    { name: 'Coquette', model: 'coquette', category: 'Sports', price: 138000, image: 'coquette' },
    { name: 'Exemplar', model: 'exemplar', category: 'Sedans', price: 205000, image: 'exemplar' },
    { name: 'Feltzer', model: 'feltzer2', category: 'Sports', price: 145000, image: 'feltzer2' },
    { name: 'Fusilade', model: 'fusilade', category: 'Sports', price: 36000, image: 'fusilade' },
    { name: 'Issi', model: 'issi2', category: 'Compacts', price: 18000, image: 'issi2' },
    { name: 'Jackal', model: 'jackal', category: 'Sedans', price: 60000, image: 'jackal' },
    { name: 'Oracle', model: 'oracle', category: 'Sedans', price: 82000, image: 'oracle' },
    { name: 'Oracle XS', model: 'oracle2', category: 'Sedans', price: 82000, image: 'oracle2' },
    { name: 'Sentinel', model: 'sentinel', category: 'Sedans', price: 95000, image: 'sentinel' },
    { name: 'Sentinel XS', model: 'sentinel2', category: 'Sedans', price: 95000, image: 'sentinel2' },
    { name: 'Surano', model: 'surano', category: 'Sports', price: 110000, image: 'surano' },
    { name: 'Zion', model: 'zion', category: 'Sedans', price: 50000, image: 'zion' },
    { name: 'Zion Cabrio', model: 'zion2', category: 'Sedans', price: 65000, image: 'zion2' },
    { name: 'Akuma', model: 'akuma', category: 'Motorcycles', price: 9000, image: 'akuma' },
    { name: 'Bagger', model: 'bagger', category: 'Motorcycles', price: 16000, image: 'bagger' },
    { name: 'Bati 801', model: 'bati', category: 'Motorcycles', price: 15000, image: 'bati' },
    { name: 'Carbon RS', model: 'carbonrs', category: 'Motorcycles', price: 40000, image: 'carbonrs' },
    { name: 'Daemon', model: 'daemon', category: 'Motorcycles', price: 20000, image: 'daemon' },
    { name: 'Double-T', model: 'double', category: 'Motorcycles', price: 12000, image: 'double' },
    { name: 'Faggio', model: 'faggio2', category: 'Motorcycles', price: 5000, image: 'faggio' },
    { name: 'Hexer', model: 'hexer', category: 'Motorcycles', price: 15000, image: 'hexer' },
    { name: 'Nemesis', model: 'nemesis', category: 'Motorcycles', price: 12000, image: 'nemesis' },
    { name: 'PCJ-600', model: 'pcj', category: 'Motorcycles', price: 9000, image: 'pcj' },
    { name: 'Blazer', model: 'blazer', category: 'Off-road', price: 8000, image: 'blazer' },
    { name: 'Brawler', model: 'brawler', category: 'Off-road', price: 715000, image: 'brawler' },
    { name: 'Dubsta 6x6', model: 'dubsta3', category: 'Off-road', price: 249000, image: 'dubsta3' },
    { name: 'Rebel', model: 'rebel', category: 'Off-road', price: 22000, image: 'rebel' },
    { name: 'Sandking XL', model: 'sandking', category: 'Off-road', price: 45000, image: 'sandking' },
    { name: 'Trophy Truck', model: 'trophytruck', category: 'Off-road', price: 550000, image: 'trophytruck' },
    { name: 'Bifta', model: 'bifta', category: 'Off-road', price: 75000, image: 'bifta' },
    { name: 'Bodhi', model: 'bodhi2', category: 'Off-road', price: 25000, image: 'bodhi2' },
    { name: 'Dune Buggy', model: 'dune', category: 'Off-road', price: 20000, image: 'dune' },
    { name: 'Kalahari', model: 'kalahari', category: 'Off-road', price: 40000, image: 'kalahari' },
    { name: 'Marshall', model: 'marshall', category: 'Off-road', price: 500000, image: 'marshall' },
    { name: 'Mesa', model: 'mesa', category: 'Off-road', price: 30000, image: 'mesa' },
    { name: 'Rancher XL', model: 'rancherxl', category: 'Off-road', price: 9000, image: 'rancherxl' },
    { name: 'Rebel (Rusty)', model: 'rebel2', category: 'Off-road', price: 3000, image: 'rebel2' },
    { name: 'Sandking SWB', model: 'sandking2', category: 'Off-road', price: 38000, image: 'sandking2' },
    { name: 'Dubsta', model: 'dubsta', category: 'SUV', price: 120000, image: 'dubsta' },
    { name: 'Landstalker', model: 'landstalker', category: 'SUV', price: 58000, image: 'landstalker' },
    { name: 'Radius', model: 'radi', category: 'SUV', price: 32000, image: 'radi' },
    { name: 'Rocoto', model: 'rocoto', category: 'SUV', price: 85000, image: 'rocoto' },
    { name: 'Seminole', model: 'seminole', category: 'SUV', price: 30000, image: 'seminole' },
    { name: 'XLS', model: 'xls', category: 'SUV', price: 253000, image: 'xls' },
    { name: 'Patriot', model: 'patriot', category: 'SUV', price: 50000, image: 'patriot' },
    { name: 'Gresley', model: 'gresley', category: 'SUV', price: 29000, image: 'gresley' },
    { name: 'Habanero', model: 'habanero', category: 'SUV', price: 42000, image: 'habanero' },
    { name: 'Huntley', model: 'huntley', category: 'SUV', price: 245000, image: 'huntley' },
    { name: 'Mesa', model: 'mesa', category: 'SUV', price: 30000, image: 'mesa' },
    { name: 'Patriot', model: 'patriot', category: 'SUV', price: 50000, image: 'patriot' },
    { name: 'Rocoto', model: 'rocoto', category: 'SUV', price: 85000, image: 'rocoto' },
    { name: 'Serrano', model: 'serrano', category: 'SUV', price: 60000, image: 'serrano' },
    { name: 'Seminole', model: 'seminole', category: 'SUV', price: 30000, image: 'seminole' },
    { name: 'XLS', model: 'xls', category: 'SUV', price: 253000, image: 'xls' },
    { name: 'Contender', model: 'contender', category: 'SUV', price: 250000, image: 'contender' },
    { name: 'Asterope', model: 'asterope', category: 'Sedans', price: 26000, image: 'asterope' },
    { name: 'Emperor', model: 'emperor', category: 'Sedans', price: 8000, image: 'emperor' },
    { name: 'Glendale', model: 'glendale', category: 'Sedans', price: 20000, image: 'glendale' },
    { name: 'Intruder', model: 'intruder', category: 'Sedans', price: 16000, image: 'intruder' },
    { name: 'Premier', model: 'premier', category: 'Sedans', price: 10000, image: 'premier' }
]